
sssp_ascetic:
	clang++ -fsycl -fsycl-targets=nvptx64-nvidia-cuda main.cpp -lpthread -Wno-unused-comparison -Wno-return-type -Wno-switch -Wno-c++20-extensions -o sssp_OneGraph 

clean:
	rm sssp_OneGraph